# 公開するページのURL
baseURL = "https://blog.pyrifolia.net"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

# ブログのタイトル
title = "Pyrifolia"

theme = "mainroad"
paginate = 20

# 自己紹介
[Author]
    name = "Pear"
    bio = "理系大学院生"
    avatar = "img/avatar.png"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "Author"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#00bfff"

# SNS等のユーザー名
[Params.widgets.social]
  github = "58"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

